version: '3.9'
services:
  postgres:
    image: postgres
    hostname: postgres
    container_name: postgres
    env_file:
      - .env
    ports:
      - '5432:5432'
    networks:
      - ndsnet
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U onestack"]
      interval: 5s
      timeout: 5s
      retries: 5

  metabase:
    container_name: metabase
    depends_on:
      - postgres
    hostname: metabase
    build: metabase/
    volumes:
      - ./conf/metabase:/conf
    ports:
      - 3030:3030
    networks:
      - ndsnet

  airflow:
    container_name: airflow
    build: ./airflow  # Adjust the path to your Airflow Dockerfile
    env_file:
      - .env
    ports:
      - 8080:8080
    volumes:
      - ./dags:/opt/airflow/dags  # Adjust the path to your Airflow DAGs directory
      - ./airflow/airflow.cfg:/opt/airflow/airflow.cfg  # Adjust the path to your Airflow configuration file
    networks:
      - ndsnet

networks:
  ndsnet:
    driver: bridge