onestack:
  target: dev
  outputs:
    dev:
      type: postgres
      host: postgres
      user: onestack
      password: onestack
      port: 5432
      dbname: onestack
      schema: public
      threads: 4
