
name: 'silver'
version: '1.0.0'
config-version: 2

profile: 'spark'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  +materialized: table
  +schema: silver    
  +properties: {"format": "'ORC'", "using": "'ICEBERG'"}
